### PR TITLE
SDK3

### PR DESCRIPTION
**Pull request by XeroxQ**
Heya, SDk3, seems to work fine with my XBox. I even got it newly installed on the HP2023, found my device (in dev mode even!) en it works.

Updated changelog.

And small update to not have to wait 2 or 4 seconds, but have the pair-discovery go based on a promise. :)

### CODE REVIEW

**Comment by kaohlive** [comment]
I am testing it with the buttons, but I get a this.client.getManager(...).sendCommand is not a function error when pressing the buttons. Did you test the functions?
Button presses control the xbox and you see what app is running?

**Comment by kaohlive** [comment]
How did you manage to get the xbox token for the account? My trick doesnt work anymore I see :(

**Comment by XeroxQ** [comment]
I will check the app better tomorrow.
For me, finding the device and turning it on off worked just fine.

Okay, just tested this: I removed the XBOX (on HP2023, so i can mess around easy).
Then i readded: Now i can push buttons, on/off, nexus, etc: everything works.
I think, after a while it stops working.
Probably because of the token?

I'll have a look later.

**Comment by kaohlive** [comment]
The token should auto refresh.
I noticed something was wrong with the settings page having an error. 
I also updated some additional nom packages.
A 5.1 version is now available in the test

I have a good working Xbox One X
But my Xbox series X is giving me the errors.
Could be that the series never worked with it, I also use it now only for the on off detection ;)

**Comment by XeroxQ** [comment]
I use it with the Xbox Series S (the little white one) and it work(ed) fine 😉

Met vriendelijke groet,

Arie J. Godschalk

Qluster IT

***@***.******@***.***>
06-25268440

[Qluster IT, Print]

Van: kaohlive ***@***.***>
Verzonden: donderdag 9 februari 2023 22:12
Aan: kaohlive/com.xbox.smartglass ***@***.***>
CC: Arie J. Godschalk ***@***.***>; Author ***@***.***>
Onderwerp: Re: [kaohlive/com.xbox.smartglass] SDK3 (PR #6)


The token should auto refresh.
I noticed something was wrong with the settings page having an error.
I also updated some additional nom packages.
A 5.1 version is now available in the test

I have a good working Xbox One X
But my Xbox series X is giving me the errors.
Could be that the series never worked with it, I also use it now only for the on off detection ;)

**Pull request merged**
